// <auto-generated />
using EducationManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EducationManagement.Migrations
{
    [DbContext(typeof(StudentContext))]
    partial class StudentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EducationManagement.Models.Classes", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ClassId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            ClassId = 4,
                            ClassName = "Science"
                        },
                        new
                        {
                            ClassId = 3,
                            ClassName = "Maths"
                        },
                        new
                        {
                            ClassId = 11,
                            ClassName = "Chemistry"
                        },
                        new
                        {
                            ClassId = 9,
                            ClassName = "Physics"
                        });
                });

            modelBuilder.Entity("EducationManagement.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 10,
                            ClassId = 4,
                            Name = "Angitha"
                        },
                        new
                        {
                            Id = 2,
                            Age = 8,
                            ClassId = 3,
                            Name = "Ashmitha"
                        },
                        new
                        {
                            Id = 3,
                            Age = 15,
                            ClassId = 11,
                            Name = "Isai"
                        },
                        new
                        {
                            Id = 4,
                            Age = 12,
                            ClassId = 9,
                            Name = "Madhu"
                        },
                        new
                        {
                            Id = 5,
                            Age = 12,
                            ClassId = 9,
                            Name = "Kiruthika"
                        },
                        new
                        {
                            Id = 6,
                            Age = 15,
                            ClassId = 11,
                            Name = "Kavya"
                        },
                        new
                        {
                            Id = 7,
                            Age = 10,
                            ClassId = 4,
                            Name = "Dharshini"
                        });
                });

            modelBuilder.Entity("EducationManagement.Models.Student", b =>
                {
                    b.HasOne("EducationManagement.Models.Classes", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("EducationManagement.Models.Classes", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
